name: rest_client
description: Rest Client library for the project
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: 1.1.0
  meta: 1.9.1
  path: 1.8.3

dev_dependencies:
  test: 1.24.6
  sizzle_lints: ^2.0.1
